name: md linter
on: push
jobs:
  md-linter:
    name: md-linter
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: lint md files
      uses: DavidAnson/markdownlint-cli2-action@v18
      with:
        globs: '**/*.md'
    - name: echo this
      run: echo "done!!!!"
